name: remote ssh command
on:
  repository_dispatch:
    types: [backend_automation]
  
jobs:
  Maintenance_on:
    if: ${{ github.event.client_payload.maintenance }}
    name: Maintenance ON
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using SSH Key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: bin/magento config:show tescomobile_customer/login/maintenance_enabled
    - name: applying maintenance page on fastly
      run: |
        curl --location --request PUT 'https://api.fastly.com/service/3lTDJqPEIavoiXpuWQ38fs/dictionary/3a7Y3c4MIY2uC7IrQbNpg6/item/enabled?item_value=true' \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --header 'Accept: application/json' \
        --header 'Fastly-Key: ${{ secrets.fastly_key }}'
  Maintenance_off:
    if: ${{ !github.event.client_payload.maintenance }}
    name: Maintenance OFF
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using SSH Key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: whoami
    - name: Disabling maintenance page on fastly
      run: |
        curl --location --request PUT 'https://api.fastly.com/service/3lTDJqPEIavoiXpuWQ38fs/dictionary/3a7Y3c4MIY2uC7IrQbNpg6/item/enabled?item_value=false' \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --header 'Accept: application/json' \
        --header 'Fastly-Key: ${{ secrets.fastly_key }}'
