name: remote ssh command
on:
  repository_dispatch:
    types: [maintenance_on, maintenance_off, status]
  
jobs:

  build:
    name: Maintenance On
    runs-on: ubuntu-latest
    if: ${{ github.event.types == 'status' }}
    steps:
    - name: executing remote ssh commands using SSH Key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: bin/magento config:show tescomobile_customer/login/maintenance_enabled
